include:
  - project: $DEEP_PIPELINE_TOOLS/pipeline
    file: pipeline.yml

variables:
  DEEP_CI_IMAGE_NAME: clamav
  DEEP_CI_IMAGE_TAG: 1.3.1

download rpms:
  stage: download
  image: $DEEP_IMAGE_REGISTRY_URL/$DEEP_REGISTRY_TOOLS_NAMESPACE/dev-tools:1.0.2
  needs: []
  script:
    - curl -L https://www.clamav.net/downloads/production/clamav-${DEEP_CI_IMAGE_TAG}.linux.x86_64.rpm -o clamav.rpm
    - curl -L https://www.clamav.net/downloads/production/clamav-${DEEP_CI_IMAGE_TAG}.linux.x86_64.rpm.sig -o clamav.rpm.sig
    - gpg --import talos.pub
    - gpg --verify clamav.rpm.sig clamav.rpm
  artifacts:
    paths:
      - clamav.rpm
      - clamav.rpm.sig

freshclam:
  stage: .pre
  image: $DEEP_IMAGE_REGISTRY_URL/$DEEP_REGISTRY_TOOLS_NAMESPACE/clamav:1.2.1
  needs: []
  script:
    - freshclam
    - mkdir -p tmp/freshclam
    - cp -r /usr/local/share/clamav/ tmp/freshclam
  artifacts:
    paths:
      - tmp/freshclam

build:
  needs:
    - job: download rpms
      artifacts: true
    - job: freshclam
      artifacts: true

test:
  extends:
    - .clamav download
  variables:
    TRIVY_VERSION: 0.50.1
    CLAMAV_DOWNLOAD_BASE_URL: https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/
    CLAMAV_DOWNLOAD_FILE_NAME: trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
    CLAMAV_DOWNLOAD_CHECKSUM_FILE_NAME: trivy_${TRIVY_VERSION}_checksums.txt
    CLAMAV_DOWNLOAD_ARTIFACT_FILE_NAME: trivy.tar.gz
